version: "2.1"
services:
  jobmanager:
    image: flink:1.18.1-java11
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
      - .:/opt/flink/usrlib
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager

  taskmanager:
    image: flink:1.18.1-java11
    depends_on:
      - jobmanager
    command: taskmanager
    volumes:
      - .:/opt/flink/usrlib
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4
